<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <ExecutablePath>..\..\3rd\Microsoft DirectX SDK %28June 2010%29\Developer Runtime\x86;$(ExecutablePath)</ExecutablePath>
    <ExternalIncludePath>..\..\3rd\Microsoft DirectX SDK %28June 2010%29\include;$(ExternalIncludePath)</ExternalIncludePath>
    <LibraryPath>..\..\3rd\Microsoft DirectX SDK %28June 2010%29\lib\x86;$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>